[package]
name = "pollard_rho"
version = "0.1.0"
edition = "2021"

[dependencies]
rug = { version="1.24.1", default-features = false, features = ["integer", "std"] }
gmp-mpfr-sys = { version="1.6.3", features = ["force-cross"] }